### ISSUE TITLE
Non-minified version

### ISSUE THREAD

**Issue by chrisdonahue** [philipwalton/mozart#1]
Please add a non-minified version of the library to the repository to allow myself and others the ability to contribute.

**Comment by philipwalton** [comment]
Would source maps be sufficient? Or do you actually want a non-minified version?

If you'd like to contribute, all of the built mozart.js file comes from the following two files:
- https://github.com/philipwalton/mozart/blob/0.1.0/index.js
- https://github.com/philipwalton/mozart/blob/0.1.0/lib/class.js

**Comment by chrisdonahue** [comment]
I didn't realize that these two files built the minified version. That should be fine, thanks!
